version: "3.9"

networks:
  kong-net:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - kong-net

  postgres:
    image: postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.7
    container_name: kong-migrations
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    image: kong:3.7
    container_name: kong-gateway
    depends_on:
      - postgres
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PORTAL_GUI_HOST: "0.0.0.0:8003"
      KONG_MANAGER_LISTEN: "0.0.0.0:8002" # Kong Manager UI
    ports:
      - "8000:8000" # Proxy
      - "8443:8443" # Proxy SSL
      - "8001:8001" # Admin API
      - "8002:8002" # Kong Manager UI
      - "8003:8003" # Dev Portal GUI (if needed)
      - "8444:8444" # Admin API SSL
    networks:
      - kong-net

volumes:
  kong-db-data:
